name: beers_pairing
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  animations: ^1.1.2
  http: ^0.12.2
  rxdart: ^0.24.1
  cached_network_image: ^2.2.0+1
  shared_preferences: ^0.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  # json_serializable:
  # build_runner:

flutter:
  uses-material-design: true
